### ISSUE TITLE
[Trinket] Mug's Moxie Jug

### ISSUE THREAD

**Issue by Mlklock** [simulationcraft/simc#10116]
### Describe the bug
Mug's Moxie Jug procs and trigger stacks beyond just spellcasting, this means a spec like Demonology in sims will generate less stacks than its Ingame Counterpart. 

### Expected behavior
> The behavior in game seems to grant stacks from things like Apply Buff (Demonic Cores, Imp Gang Boss transformation), Applying Debuffs (Wicked Maw debuff), Spell Casting (Shadow Bolt, Call Dreadstalkers), Damage Events (Shadow bolt, Hand of Guldan).
>
> There are some background and other effects who also grant it, but those are beyond the scope of simc (defensives, summoning pet, some skills). 
>
> Of course, the granting of stacks does seems to obey the 0.75s ICD, but it is possible to Proc and Gain a stack in quick sucession and at a interval smaller than those 0.75s (screenshot/log provided in this report). 

### To Reproduce
>
> Proc the Trinket/Gain Stacks of the trinket across different actions and then check a combatlog in warcraftlogs to compare.

### Additional information
> Log where nothing is done but it procs and gains stacks from simply Wild Imps spawning from the Inner Demon Talent /becoming Imp Gang Bosses : https://www.warcraftlogs.com/reports/dHhLaDGnyfQR9gbp?fight=14&type=summary&source=16&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24152690636.0.0.Warlock%24false%24474285&start=7632321&end=7671378&view=events 
>
>Log where it procs from both the Shadowbolt Cast at 1:16  bu also from its hit at 1:17.6 : https://www.warcraftlogs.com/reports/PNcwm9BMgDTZzjr8?fight=10&type=summary&source=16&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24152690636.0.0.Warlock%24false%24474285%5E2%24Off%24%23909049%24expression%24not+ability.name+%3D+%22firebolt%22&view=events 
>
>Screenshot of Log 1 where Wild Imp 9 spawns and gains Imp Gang Boss buff from the warlock activating it and stacking it to 2,  https://i.imgur.com/7UUZYgE.png
>
> Screenshot of Log 2 where Shadowbolt cast and damage grant stacks https://i.imgur.com/6Gl3zeJ.png
>
> Log where Call Dreadstalker cast both proc it (probably from the cast) and grant a stack (for some reason)  then grants another stac at 14s due to granting Demonic Cores buff being gained/generated: https://www.warcraftlogs.com/reports/yaPX4hxCBmH7rdwb?fight=24&type=casts&source=16&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24152690636.0.0.Warlock%24false%24474285&view=events 
>https://i.imgur.com/W0hN9Rf.png Screenshot of the Demonic Core event. 
>
> Might be interesting to check at other classes as well if buffs/debuffs also seems to trigger it.

**Comment by Mlklock** [comment]
In the ground of discussion, the log provided above with Call Dreadstalker did not have Wicked Maw talented, yet it was able to proc (from the cast), but also grant a stack. 

This stack could have be due to the Summon Event, would at least explain why Inner Demons Wild Imps seems to grant stacks of it.

**Comment by gastank** [comment]
Both summons and energize would count as generic heal, which can trigger the stacking buff driver. The procs off shadowbolt "cast" is most likely actually from the separate soul shard energize spell. Demonic core also isn't just a buff, it's a separate projectile that travels back from the dreadstalkers that hits the player and it's the projectile that applies the buff, and that's most likely what's actually triggering the stack.

So far the logs you've provided don't suggest the trinket is acting any strangely, it seems more the peculiarities with how the warlock spells are coded in game that would require adjustments in the warlock module. Would need more investigations into other more spells/specs with more standardized implementation to see if the trinket itself is behaving unexpectedly.

**Comment by Twinkeli** [comment]
After testing/looking at more logs the stack from shadow bolt cast is indeed from energize (not cast) and the energize event seems to work on other classes as well (ingame atleast), but not on certain abilities like shooting stars (maybe because of the not a proc or treat as periodic flags?)

And since cast events don't give stacks it has to be the projectile or aura application?

Some Warlock spells that don't have any projectiles but give stacks:

Infernal Command 01:06.862 / 01:07.684 / 01:08.474 / 01:10.887 (log is full of stacks from this)
Wicked Maw (applied when pet dreadbites but source is player) 01:11.912 / 03:22.827 / 03:29.291
Cloven Soul (same as above but diff pet) 01:49.594 / 
Soul Leech 02:09.789 / 02:36.905
https://www.warcraftlogs.com/reports/a7CytfZ3YAPQG4c1?fight=1&type=summary&source=2&pins=0%24Main%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24152690636.0.0.Warlock%24false%24474285&view=events&start=21074278&end=21228821

Nightfall
https://www.warcraftlogs.com/reports/CFbnTXKk1PRzcVfG?fight=19&type=auras&source=3&view=events

Summoning Disorientation
https://www.warcraftlogs.com/reports/7xZgCPd13DrqHjXY?fight=6&source=10&type=summary&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24152690636.0.0.Unknown%24false%24474285&view=events&start=664846&end=676197

From curse & fel domination, fear and shadowfury don't give stacks since the dummy is immune
https://www.warcraftlogs.com/reports/CFbnTXKk1PRzcVfG?fight=8&type=summary&source=3&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24152690636.0.0.Warlock%24false%24474285&start=3488032&end=3513416&view=events

Same as above but fear and shadowfury give a stack since its not immune
https://www.warcraftlogs.com/reports/CFbnTXKk1PRzcVfG?fight=9&type=summary&source=3&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%24152690636.0.0.Warlock%24false%24474285&view=events&start=3789306&end=3806447

Don't have a log of but work: Unending Resolve,Dark Pact, Demonic Circle: Teleport, Soulburn, Malevolence, Immolate energize, taking demonic gateway

Most of these are irrelevant for sim purposes but listed everything anyways

**Comment by gastank** [comment]
Soul leech is just a standard heal/absorb cast by the player so that's expected, and same with defensives/utility/curses etc. which are just generic hostile/helpful actions. 

SimC doesn't properly handle non-damaging impact procs from things like defensives/utilities/etc so that'll need to get fixed in core.

The rest are scripted, so hard to say what's specific to the trinket, and what's specific to how warlock is coded. My guess is the pet applied debuffs are actually separate scripted actions by the player hence they proc generic hostile triggers. Similarly with nightfall as that is entirely a hidden script and if it actually is an accumulator server-side, it would likely use a scripted generic helpful action to apply the buff to the player.

I'm not sure how infernal command works (couldn't find mention of it in the warlock module) but it looks like it's not immediately applied on summon? It might be on a hidden periodic scripted timer which would add another scripted generic helpful action to the warlock when it "ticks" to buff the imp.

**Comment by Mlklock** [comment]
Infernal command is an aura who the felguard have, it used to be a talent who gave 5% damage increase to wild imps and dreadstalkers but blizzard removed said talent, the effect still exists but as a 0% damage increase instead. 

As for Wicked Maw, you are correct that its a script who the player apply and not the pet.

**Comment by gastank** [comment]
Infernal command is sourced to the player so it sounds like it was also scripted back when it was implemented and the script is still running to this day.

I suspect all this would need to get implemented into the warlock module (once the core changes are made to allow non-damaging generic spells to proc appropriate triggers), as it wouldn't just affect this trinket but every other effect with generic hostile/helpful triggers. The difference would generally be minimal since most things are RPPM, but there may be cases where the RPPM wasn't being saturated with damage spells, but now will be with these additional triggers.

**Comment by Mlklock** [comment]
In the case of any other RPPM trinket it wouldn't matter much,  but given that each valid action gives a stack after the original proc, it makes the simulate generate less stacks than compared to ingame. 

https://www.raidbots.com/simbot/report/bBR51xtnAT5dKbNn2UPZTB/simc :  https://i.imgur.com/dyuBP1N.png ; https://i.imgur.com/y4LOKgq.png 

adding a log https://www.warcraftlogs.com/reports/CZvdhAN9RK2Y31L7?fight=31&type=auras&source=118&ability=474285 stack builtup ingame to compare.
