### ISSUE TITLE
[Brewmaster Monk]: Sal'salabim's Lost Tunic's effect not working

### ISSUE THREAD

**Issue by mokooo** [simulationcraft/simc#3310]
Hi,

Simming i noticed the breath of fire interval was abnormally long (always over 15 seconds) with Sal'salabim's Lost Tunic (the legendary chest that resets the cooldown of breath of fire when keg smash is used), so i decided to sim using an apl just using keg smash and breath of fire, and the interval beetween breath of fire casts was still around 15 seconds(base cd), meaning the effect doesn't work.

http://i.imgur.com/t6XgRgv.png

Simulationcraft Version: 715-01

#### Reproduction Steps:
I used this sim profile:

http://pastebin.com/sfRby9d8

Thanks for the fast Keg Smash fix!

**Comment by ManagerWoW** [comment]
Adding to the list:

Face Palm is a 200% mod, not 300%.
Niuzao should have a 2s attack speed, not 1.5s
Blackout Combo crashes Simc instantly

**Comment by Collisionc** [comment]
Ok, I think I fixed everything. Let me know if there are other issues .

**Comment by mokooo** [comment]
Hello,
Thanks for the fixes but

-Tiger palm value is wrong, with rough maths my average tp should be

1.05(base spell)*1.1033(versa)*31486(ap)*1.28(crit)*1.255(mastery)*3(blackout combo)*2.2(average modifier with 3 face palm relics)=387k  (not even factoring the angerboda procs i was getting during the sim), it's actually a little bis less than that because of the bosses armor but in the sim i get an average tp around 250k comboing every of them, so something is off here

-Barbed rebuke is broken, i can get it doesn't proc from stagger because stagger isn't implemented but it does around 20k damage non crit in game and 384 in the sim

**Comment by ManagerWoW** [comment]
Tiger Palm damage is correct. Blackout Combo & Face Palm are also correct. List of modifiers:

- Tiger Palm: 1.05
- Brewmaster Monk: 0.90
- Brewmaster Monk: 1.09
- Artificial Damage (60 traits): 1.30
- Armor (113): 0.6802

Barbed Rebuke is still broken, though I'm trying to make a custom on-use item to simulate it.

**Comment by mokooo** [comment]
it's really not, check logs there is no world where the average tp is around 250k with high gear, with poor rng it's around 300k and with a good one it's around 350k, there is definitely something wrong (and the previous build seemed accurate for tp damage), if you factor in what i forgot (armor traits and brm multipliers) you get
387* 0.9* 1.09* 1.26(52 traits)* 0.6802=325k, when even with really high iterations my average tp is around 250k in simcraft and my apl doesnt use non combod tiger palms

**Comment by Collisionc** [comment]
stupid barbed rebuke

**Comment by Collisionc** [comment]
Ok, had to get navv to fix the neck - https://github.com/simulationcraft/simc/commit/28c4864a5aeca6c9993599054bbf29c199a01a1b

should work now.

**Comment by ManagerWoW** [comment]
Barbed rebuke is probably going to need special coding. It always hits for 15,000 damage, regardless of item level. It ignores armor. It doesn't scale with AP. It does scale with mods (versatility / artificial damage..etc)

Stagger is still not proccing it, but even if that gets fixed, there's the issue that stagger still ticks every 1s, instead of 0.5s in Simc (intentional, to reduce events). Might not be worth fixing in the end

---

Exploding Keg is using a 1.5s GCD, instead of 1s

Breath of Fire GCD is using a hasted 1.5s GCD, instead of 1s

Rushing Jade Wind's cooldown/duration/ticks should be hasted

Special Delivery can be blocked

Barbed Rebuke can be blocked

----

http://manager.heroicstrike.org/2017-01-16_02-27-55.png

The Sample Sequence Table is using the timestamp when a spell is queued up, not actually executed. Example in the picture: RJW is casted every 6s, but Simc is showing when it is queued up 0.2s ahead of time.

```
5.804 Executing event: Player-Ready
5.804 action_t::cost: rushing_jade_wind base_cost=0.00 secondary_cost=0.00 cost=0.00 resource=chi
5.804 Add Event: core_event_t time=6.0000 rs-time=0.0000 id=114

6.000 Manager schedules execute for rushing_jade_wind_tick
6.000 Add Event: core_event_t time=6.0000 rs-time=0.0000 id=115
6.000 New Action Execute Event: Manager rushing_jade_wind_tick 0.0 (target=Fluffy_Pillow, marker=0)
```

**Comment by navv1234** [comment]
Aha, interesting. Good info on that 15k thing.

**Comment by Collisionc** [comment]
so barbed rebuke cannot crit?

**Comment by ManagerWoW** [comment]
It can crit

**Comment by Collisionc** [comment]
See if the damage looks about right now, it's hitting for around 18k constantly with a random prot warrior i'm using... i think it has enough versatility to do that.

**Comment by ManagerWoW** [comment]
Damage looks good, just need to make it be blockable.

**Comment by Collisionc** [comment]
what about parry ?

**Comment by ManagerWoW** [comment]
Unsure, and hard to test. Guessing it can, but it won't matter for tanks.
