### ISSUE TITLE
Simcraft has stopped working!

### ISSUE THREAD

**Issue by Jumpywizard96** [simulationcraft/simc#3399]
Every time i try to simulate, its loading after i click simulate and then its says Simulationcraft has stopped working.

Please include a brief overview of the issue in the title above, as well as completing the following:

#### If Simulationcraft is crashing, please include your dxdiag file 
[DxDiag.txt](https://github.com/simulationcraft/simc/files/706767/DxDiag.txt)

#### simc_gui.simc file or contents 
[simc_gui.zip](https://github.com/simulationcraft/simc/files/706770/simc_gui.zip)

**Comment by Collisionc** [comment]
We actually literally added something that may help fix this in the upload I just made. 

http://downloads.simulationcraft.org/?C=M;O=D

Let us know if that does anything for you.

**Comment by Jumpywizard96** [comment]
Nope the same problem

**Comment by Collisionc** [comment]
Normally I'd forward you to the solution, but if you don't mind, can you test something for us ? 

Basically, your computer has a program that is crashing Simulationcraft's web browser, and removing the program (it's typically classified as malware) fixes it, but  @navv1234 is working on a way to force unload the program so that it doesn't crash Simulationcraft. 

So, if you're ok with being a tester we'll upload another version sometime today that will have a possible fix so that others don't run into this

If you don't want to wait, then the first solution here -
 https://github.com/simulationcraft/simc/wiki/CommonIssues  - should fix the problem.

**Comment by Collisionc** [comment]
Ok, we tried a different way of fixing it here, redownload here - http://downloads.simulationcraft.org/?C=M;O=D

Let us know if it works or not, and then remove lavasoft's web companion because it's probably screwing up other things on your computer. :)

**Comment by exoursia** [comment]
Hello,
I have the same problem now occurring to me with 7.2.0 release. I downloaded the latest version and still cant open it. Can you help me out plz??

Thanx
